### ISSUE TITLE
 I can't generate a complete language package.

### ISSUE THREAD

**Issue by lvdongmao** [hhd-software/hex-editor-localization-pack#10]
why I can't generate a complete language package.

![image](https://user-images.githubusercontent.com/104017946/209847360-c30eaab7-42d6-4848-a619-c466c2e1e7dd.png)

![image](https://user-images.githubusercontent.com/104017946/209847268-bf663968-fb79-4015-b11f-6c89afd0f966.png)

**Comment by AlexBAV** [comment]
Could you please share the sources so we could reproduce this?

**Comment by lvdongmao** [comment]
Thank you for your reply！
1. I git clone this
![image](https://user-images.githubusercontent.com/104017946/209970755-d495abf7-3eba-46d3-b634-6f0fe7224c75.png)
2. I open langtool.exe and open hex.xml
![image](https://user-images.githubusercontent.com/104017946/209970927-f7dd6f88-d598-455c-bb1d-18d056bb6801.png)
3.I add one language .
![image](https://user-images.githubusercontent.com/104017946/209971061-6395cc0e-7775-4c0c-831e-0eb370053557.png)
![image](https://user-images.githubusercontent.com/104017946/209971106-e61832e7-82f0-4d3f-80a4-253b6e8b98a3.png)

4.compile
![image](https://user-images.githubusercontent.com/104017946/209971201-613a1f0d-f1cc-426b-9138-d9efa8491e84.png)
5.I  find it,just 1kb。 I can not use it in HEX.
![image](https://user-images.githubusercontent.com/104017946/209971460-874819d6-c00b-4b08-a564-be7e8506318b.png)
Maybe I didn't do that right？

**Comment by AlexBAV** [comment]
You have added new language and initially it is empty. When you export (or "compile"), only localized strings gets exported. Since the current language pack is empty, the exported file contains no strings.

This behavior is expected.

Note that this repository is for those who wants to contribute new localizations or correct existing ones. Current list of completed language packs is provided in repository's [README](/hhd-software/hex-editor-localization-pack).

**Comment by lvdongmao** [comment]
thank you, It was my misunderstanding
